
import { GoogleGenAI, Type } from "@google/genai";

export const handler = async (event: any) => {
  if (event.httpMethod !== "POST") {
    return { statusCode: 405, body: JSON.stringify({ error: "Method Not Allowed" }) };
  }

  try {
    const { sourceDoc, dirtyFeedbackDoc } = JSON.parse(event.body);

    if (!process.env.API_KEY) {
      return { 
        statusCode: 500, 
        body: JSON.stringify({ error: "API Key missing in environment." }) 
      };
    }

    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    const systemInstruction = `
      You are the Master Medical Evaluator for Anatomy Guru.
      
      CORE OBJECTIVE:
      You are transforming manual faculty notes into a professional digital feedback report. 
      The marks are already decided by a human; your job is to extract them faithfully and provide the justification.

      INPUTS:
      1. SOURCE DATA (Student Answer Sheet): Contains the actual medical answers written by the student.
      2. FACULTY EVALUATION DATA (Faculty Notes): Contains handwritten or scrawled marks and brief comments per question.

      STRICT RULES:
      - MARKS EXTRACTION: Go through the Faculty Evaluation Data. Extract the EXACT marks assigned to each question. DO NOT invent new marks. If a mark is 3/5, the result is 3.
      - GAP ANALYSIS FEEDBACK: For every question, look at the Student Answer Sheet. Identify what is missing or incorrect in the student's answer based on the marks deducted by the faculty. 
      - Provide 3-5 high-impact bullet points per question that explain "Why these marks were given" and "What was missing from the answer" to help the student improve.
      - USE MEDICAL TERMINOLOGY: Ensure all feedback is professional and uses standard anatomical/medical terms.
      - OUTPUT: Valid JSON only.
    `;

    // Priority handling: If text exists, we use it to avoid expensive vision processing.
    const sourceParts: any[] = [{ text: "STUDENT ANSWER SHEET (SOURCE):" }];
    if (sourceDoc.text) {
      sourceParts.push({ text: sourceDoc.text });
    } else if (sourceDoc.base64) {
      sourceParts.push({ inlineData: { data: sourceDoc.base64, mimeType: sourceDoc.mimeType } });
    }

    const feedbackParts: any[] = [{ text: "FACULTY MANUAL FEEDBACK (TRUTH FOR MARKS):" }];
    if (dirtyFeedbackDoc.text) {
      feedbackParts.push({ text: dirtyFeedbackDoc.text });
    } else if (dirtyFeedbackDoc.base64) {
      feedbackParts.push({ inlineData: { data: dirtyFeedbackDoc.base64, mimeType: dirtyFeedbackDoc.mimeType } });
    }

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        {
          parts: [
            ...sourceParts,
            ...feedbackParts,
            { text: "GENERATE COMPLETE STRUCTURED EVALUATION JSON BY EXTRACTING MARKS FROM FACULTY NOTES AND ANALYZING GAPS IN STUDENT ANSWERS." }
          ]
        }
      ],
      config: {
        systemInstruction,
        temperature: 0.1, // Low temperature for factual extraction
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            studentName: { type: Type.STRING },
            testTitle: { type: Type.STRING },
            testTopics: { type: Type.STRING },
            testDate: { type: Type.STRING },
            totalScore: { type: Type.NUMBER, description: "Sum of extracted marks" },
            maxScore: { type: Type.NUMBER },
            questions: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  qNo: { type: Type.STRING },
                  feedbackPoints: { 
                    type: Type.ARRAY, 
                    items: { type: Type.STRING },
                    description: "Feedback points generated by comparing student answer to expected perfection based on faculty marks."
                  },
                  marks: { type: Type.NUMBER, description: "EXACT mark extracted from faculty notes" }
                },
                required: ["qNo", "feedbackPoints", "marks"]
              }
            },
            generalFeedback: {
              type: Type.OBJECT,
              properties: {
                overallPerformance: { type: Type.STRING },
                actionPoints: { type: Type.ARRAY, items: { type: Type.STRING } }
              },
              required: ["overallPerformance", "actionPoints"]
            }
          },
          required: ["studentName", "testTitle", "questions", "generalFeedback"]
        }
      }
    });

    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" },
      body: response.text,
    };
  } catch (error: any) {
    console.error("Evaluation Function Error:", error);
    return {
      statusCode: 500,
      body: JSON.stringify({ 
        error: `AI Evaluation Error: ${error.message || "Unknown error"}. Ensure faculty notes have clear marks.` 
      }),
    };
  }
};
